### ISSUE TITLE
You just gonna leave your client secret public and give it mod access?

### ISSUE THREAD

**Issue by dbgrigsby** [xXAligatorXx/Infinity-Gauntlet#1]
https://github.com/xXAligatorXx/Infinity-Gauntlet/blob/dfbf127a5c54fe874b2746798b876280f3cfedc2/reddit.py#L8

**Comment by noamalffasy** [comment]
Is it possible to delete the bot when it finishes banning the users?

**Comment by A1igator** [comment]
yeah lol so when I realized that it was too late. The bot with that client password is now dead tho and I have created a new one so don't worry about it.
