### ISSUE TITLE
Bot can ban itself?

### ISSUE THREAD

**Issue by sasthana5** [xXAligatorXx/Infinity-Gauntlet#4]
I’m pretty new to making a bot, but I don’t see a way for the bot to ignore itself currently.

**Comment by A1igator** [comment]
Uhm I'm not really sure if mods can ban themselves. Anyhow I'll make sure the bot has the required flair before starting the script

**Comment by thecsw** [comment]
That is against the plot! Where is the pure random principle?

**Comment by TheIronNinja** [comment]
It could be made as a 50% chance ban to himself at the end of the program.
