### ISSUE TITLE
The bot wouldn't make it fast enough.

### ISSUE THREAD

**Issue by thecsw** [xXAligatorXx/Infinity-Gauntlet#6]
You have ~147000 individual users to parse. Okay, let's assume that a half comment at least once, you would need ~60 hours to process them and ~30 hours to ban a half.

``` python
>>> ((3 * (147000 / 2)) / 3600)
61.25
```
Because after your every action, you sleep for 3 seconds.

But what really bothers me is the logic of the bot. Instead of sequentially banning users, why not ban them in a very short interval of time? Like a snap of a finger? I am working on a solution right now too.

**Comment by thecsw** [comment]
Also, if I remember correctly, the line below returns only ~1000 last comments. That is the limit even if you define otherwise
``` python
for comment in Subreddit.comments():
```

**Comment by A1igator** [comment]
I am also working on a similar solution but using flairs
